apiVersion: v1
kind: ReplicationController
metadata:
  name: zookeeper-monitor
spec:
  replicas: 1
  triggers:
    - imageChangeParams:
        automatic: true
        containerNames:
        - server-monitor
        from:
          kind: ImageStreamTag
          name: "zookeeper:v18"
          namespace: openshift
        lastTriggeredImage: ""
      type: ImageChange
    - type: ConfigChange
  template:
    metadata:
      labels:
        app: monitor-zookeeper
    spec:
      containers:
        - name: server
          image: ' '
          imagePullPolicy: IfNotPresent
          env:
            - name: MYID
              value: "monitor"
