apiVersion: v1
kind: ResourceQuota
metadata:
  name: quota
spec:
  hard:
    cpu: "8"
    memory: 15Gi
    persistentvolumeclaims: "10"
    pods: "30"
    replicationcontrollers: "300"
    resourcequotas: "1"
    secrets: "10"
    services: "30"
