mysql:
  image: chw717/mysql:latest
  container_name: mysql
  net: host
  ports:
    - 3306:3306
  environment:
    MYSQL_ROOT_PASSWORD: "vpclub.dev!"
  volumes:
    - ./mysqlConf:/etc/mysql/conf.d
    - ./data/mysql:/var/lib/mysql
  
mongodb:
  image: hub.docker.vpclub.cn/vpclub/mongodb:latest
  container_name: mongodb 
  ports:
    - 27017:27017
    - 28017:28017
  volumes:
    - ./data/mongodb:/data/db
#redis-cluster
redis-master:
  image: redis:latest
  container_name: redis-master
  volumes:
    - ./data/redis/master:/data
  ports:
    - 6379:6379

redis-slave1:
  image: redis:latest
  container_name: redis-slave1
  volumes:
    - ./redis-conf/6380:/usr/local/etc/redis/
    - ./data/redis/slave1:/data
  command: redis-server /usr/local/etc/redis/redis.conf --appendonly yes
  ports:
    - 6380:6379
  links:
    - redis-master
