fastdfs-storage:
  image: vpclub/fastdfs-storage
  container_name: fastdfs-storage
  net: host
  ports:
    - 23000:23000
    - 8200:8200
  volumes:
    - ./fdfs/group1:/etc/fdfs/
    - ./nginx/conf:/usr/local/nginx/conf
    - /data:/data

