apiVersion: v1
kind: DeploymentConfig
metadata:
  name: management-center
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: management-center
    spec:
      containers:
      - name: hazelcast
        image: hazelcast/management-center:3.7.4
---
kind: Service
apiVersion: v1
metadata:
  name: management
spec:
  selector:
    app: management-center
  ports:
  - port: 8080
    targetPort: 8080
    protocol: TCP
