# application properties

server:
  port: 9995

spring:
  datasource:
    name: testdb
    url: jdbc:mysql://112.74.129.206:3306/vp_coupon_config?useUnicode=true&characterEncoding=utf-8
    username: root
    password: mQO7NpV1ohNjA37/xSIsNCIlVY4woR+zuAyeD3dBPpwcUX75gsZbvJftqhtpESDvItn6MUlJwrAAsi5+65fySQ==
    # using druid data source
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    maxActive: 20
    initialSize: 1
    maxWait: 60000
    minIdle: 1
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: select 'x'
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxOpenPreparedStatements: 20
    # encrypt password::wq

    filters: config
    connectionProperties: "config.decrypt=true"

  dubbo:
    basePackages: cn.vpclub.monitor.provider

    application:
      name: vp-monitor-provider
      owner: vpclub

    protocol:
      name: dubbo
      port: 21660
      accesslog: true

    provider:
      timeout: 30000
      retries: 1
      delay: -1

    registry:
      address: zookeeper://172.16.5.30:2181
      register: true
      subscribe: true

  http:
    encoding.charset: UTF-8
    encoding.enable: true
    encoding.force: true
  redis:
      database: 2
      host: 172.16.5.23
      password:
      port: 6379
      pool:
        max-idle: 8
        min-idle: 0
        max-active: 8
        max-wait: -1
     #  sentinel:
        # name of Redis server
        # master:
        # comma-separated list of host:port pairs
       #  nodes:
# LOGGING
logging:
  level:
     tk.mybatis: DEBUG